#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun  9 10:53:01 2023

This library contains dictionaries and values useful as a reference for other
scripts used in TC Bench

@author: mgomezd1
"""

# %% Library Imports
import numpy as np
import pandas as pd


# %% Columns for track files
class track_cols:
    def __init__(self, **kwargs):
        for key, val in kwargs.items():
            if key != "__META":
                setattr(self, key, val)
            else:
                self.__metadata = val

    def get_dtypes(self):
        dtype_dict = {}

        for key, dtype in self.__dict__.items():
            if key[0] != "_":
                dtype_dict[key] = (
                    str
                    if (isinstance(dtype, dict) or np.issubdtype(dtype, np.datetime64))
                    else dtype
                )
        return dtype_dict

    def get_colnames(self):
        colnames = []
        for key, dtype in self.__dict__.items():
            if key[0] != "_":
                colnames.append(key)
        return colnames

    def get_datetime_cols(self):
        datetime_cols = []

        for key, dtype in self.__dict__.items():
            if dtype == np.datetime64:
                datetime_cols.append(key)
        return datetime_cols


# Track column data for tracks prepared by Dr. Saranya Ganesh Sudheesh
sgs_track_cols = track_cols(  # Basin Corresponts to ibtracs basin
    basin={
        "NA": "North Atlantic",
        "EP": "Eastern North Pacific",
        "WP": "Western North Pacific",
        "NI": "North Indian",
        "SI": "South Indian",
        "SP": "South Pacific",
        "SA": "South Atlantic",
    },
    # Region Corresponts to ibtracs subbasin
    region={
        "MM": "Missing",
        "CS": "Caribbean Sea",
        "GM": "Gulf of Mexico",
        "CP": "Central Pacific",
        "BB": "Bay of Bengal",
        "AS": "Arabian Sea",
        "WA": "Western Australia",
        "EA": "Eastern Australia",
    },
    # Name of the storm
    name=str,
    # Track step
    no=int,
    # Track point timestamp
    datetime=np.datetime64,
    # Intensity corresponds to ibtracs nature
    intensity={
        "DS": "Disturbance",
        "TS": "Tropical",
        "ET": "Extratropical",
        "SS": "Subtropical",
        "NR": "Not Reported",
        "MX": "Mixture",
    },
    # Coordinates
    lat=np.float16,
    lon=np.float16,
    # Metadata for constructing track objects
    __META={
        "UID": "SID",
        "COSMETIC_NAME": "NAME",
        "Y_coord": "lat",
        "X_coord": "lon",
        "TIME_coord": "datetime",
        "loader": pd.read_csv,
    },
)

# Track column data for ibtracs file
ibtracs_cols = track_cols(  # Storm ID number
    SID=str,
    # Year of the event
    SEASON=int,
    # Number of event in season CURRENTLY IGNORED
    # NUMBER = int
    # Basin
    BASIN={
        "NA": "North Atlantic",
        "EP": "Eastern North Pacific",
        "WP": "Western North Pacific",
        "NI": "North Indian",
        "SI": "South Indian",
        "SP": "South Pacific",
        "SA": "South Atlantic",
        "MM": "Missing",  # Note that MM should not appear in final ibtracs product
    },
    # Subbasin
    SUBBASIN={
        "MM": "Missing",
        "CS": "Caribbean Sea",
        "GM": "Gulf of Mexico",
        "CP": "Central Pacific",
        "BB": "Bay of Bengal",
        "AS": "Arabian Sea",
        "WA": "Western Australia",
        "EA": "Eastern Australia",
    },
    # Name of the storm provided by the agencies
    NAME=str,
    # Track point ISO timestamp
    ISO_TIME=np.datetime64,
    # IBTRACS Combined storm type
    NATURE={
        "DS": "Disturbance",
        "TS": "Tropical",
        "ET": "Extratropical",
        "SS": "Subtropical",
        "NR": "Not Reported",
        "MX": "Mixture",
    },
    # Coordinates
    LAT=np.float16,
    LON=np.float16,
    # US Automated Tropical Cyclone Forecasting System ID
    USA_ATCF_ID=str,
    # Intensity and Pressure
    USA_WIND=str,
    USA_PRES=str,
    # Metadata for constructing track objects
    __META={
        "UID": "SID",
        "COSMETIC_NAME": "NAME",
        "Y_coord": "LAT",
        "X_coord": "LON",
        "TIME_coord": "ISO_TIME",
        "loader": pd.read_csv,
        "ALT_ID": "USA_ATCF_ID",
    },
)

# Track column data for Meteo France La Reunion file
reunion_track_cols = track_cols(  # Storm Season
    SAISON=int,
    # Name of the storm
    NOM_CYC=str,
    # Seasonal number of the depression
    NUM_DEPR=int,
    # Storm ID
    ID=str,
    # Track point timestamp
    ANNEE=np.datetime64,
    MOIS=np.datetime64,
    JOUR=np.datetime64,
    HEURE_UTC=np.datetime64,
    # Coordinates
    LAT=np.float16,
    LON=np.float16,
    # Metadata for constructing track objects
    __META={
        "UID": "ID",
        "COSMETIC_NAME": "NOM_CYC",
        "Y_coord": "LAT",
        "X_coord": "LON",
        "TIME_coord": "date",
        "loader": "meteo_france",
    },
)

# %% Folder Structure Long Names
# The folder dictionary is used to expand the folder names to their full
# names. This is useful for the user to understand what the folder names
# mean.
# The ERA5 folder structure is organized by single level, pressure level, and
# calculated values.
data_store_names = {
    "SL": "Surface / Single Level",
    "PL": "Pressure Level",
    "CV": "Calculated Values",
}

# %% valid coordinate names
valid_coords = {
    "latitude": ["lat", "Lat"],
    "longitude": ["lon", "Lon"],
    "time": ["time", "Time", "t"],
    "level": ["Lev", "lev", "pressure", "Pressure"],
}


# %% PRIMED Metadata
# Questions for developers:
# Why are the files organized by these basins but the metadata includes
# basins? Why are the basins not the same?
primed_basins = set(
    [
        "AL",  # North Atlantic
        "CP",  # Central Pacific
        "EP",  # Eastern North Pacific
        "IO",  # Indian Ocean
        "SH",  # Southern Hemisphere
        "WP",  # Western North Pacific
    ]
)

# Primed storm names are stored in a nested dictionary, the first key dedicated
# to the year and the second key dedicated to the storm ID. Note that this has
# currently only been applied to the North Atlantic basin. For storms without a name,
# the dictionary return by the year should be called using the .get() method.
# e.g., psn[study_year].get(STORM_ID, 'Unnamed')
# Primed Storm Names abbreviated to psn
# UPDATE: - No longer using this dictionary. Primed uses the ATCF ID as the
#           storm ID, so we can use the ATCF ID to get the storm name.
psn = {
    2000: {
        3: "Alberto",
        10: "Florence",
        11: "Gordon",
        12: "Helene",
        13: "Isaac",
        14: "Joyce",
        15: "Keith",
        16: "Leslie",
    },
    2001: {
        1: "Allison",
        3: "Barry",
        4: "Chantal",
        5: "Dean",
        6: "Erin",
        7: "Felix",
        8: "Gabrielle",
        10: "Humberto",
        11: "Iris",
        15: "Michelle",
        17: "Olga",
    },
    2002: {4: "Dolly", 8: "Gustav", 10: "Isidore", 12: "Kyle", 13: "Lili"},
    2003: {
        1: "Ana",
        4: "Claudette",
        5: "Danny",
        10: "Fabian",
        13: "Isabel",
        16: "Kate",
        17: "Larry",
        19: "Nicholas",
    },
    2004: {
        1: "Ana",
        2: "Bonnie",
        3: "Charley",
        4: "Danielle",
        6: "Frances",
        7: "Gaston",
        9: "Ivan",
        11: "Jeanne",
        12: "Karl",
        13: "Lisa",
        16: "Otto",
    },
    2005: {
        1: "Arlene",
        3: "Cindy",
        4: "Dennis",
        5: "Emily",
        6: "Franklin",
        8: "Harvey",
        9: "Irene",
        12: "Katrina",
        13: "Lee",
        14: "Maria",
        15: "Nate",
        16: "Ophelia",
        17: "Philippe",
        18: "Rita",
        25: "Wilma",
        28: "Gamma",
        29: "Delta",
        30: "Epsilon",
        31: "Zeta",
    },
    2006: {
        1: "Alberto",
        5: "Debby",
        6: "Ernesto",
        7: "Florence",
        8: "Gordon",
        9: "Helene",
    },
    2007: {
        1: "Andrea",
        4: "Dean",
        6: "Felix",
        8: "Ingrid",
        11: "Jerry",
        12: "Karen",
        14: "Melissa",
        16: "Noel",
        17: "Olga",
    },
    2008: {
        # 1: "Arthur",
        2: "Bertha",
        # 3: "Cristobal",
        4: "Dolly",
        # 5: "Edouard",
        6: "Fay",
        7: "Gustav",
        8: "Hanna",
        9: "Ike",
        10: "Josephine",
        # 11: "Kyle",
        12: "Laura",
        # 13: "Marco",
        # 14: "Nana",
        15: "Omar",
        17: "Paloma",
    },
    2009: {
        2: "Ana",
        3: "Bill",
        # 4:'Claudette',
        # 5:'Danny',
        # 6:'Erika',
        7: "Fred",
        9: "Grace",
        # 10:'Henri',
        11: "Ida",
    },
}

# %% Metpy units
[
    "%",
    "A",
    "A_90",
    "A_US",
    "A_it",
    "Ah",
    "At",
    "B",
    "BDFT",
    "BF",
    "BTU",
    "Ba",
    "Bd",
    "Bi",
    "Bq",
    "Btu",
    "Btu_iso",
    "Btu_it",
    "Btu_th",
    "C",
    "C_90",
    "Ci",
    "Cl",
    "Context",
    "D",
    "DPI",
    "Da",
    "ECC",
    "EC_therm",
    "E_h",
    "Eh",
    "F",
    "FBM",
    "F_90",
    "Fr",
    "G",
    "G_0",
    "Gal",
    "Gb",
    "Group",
    "Gy",
    "H",
    "H2O",
    "H_90",
    "Hg",
    "Hg_0C",
    "Hg_32F",
    "Hg_60F",
    "Hz",
    "J",
    "K",
    "KPH",
    "K_J",
    "K_J90",
    "K_alpha_Cu_d_220",
    "K_alpha_Mo_d_220",
    "K_alpha_W_d_220",
    "L",
    "Ly",
    "M",
    "MPH",
    "Measurement",
    "Mx",
    "N",
    "N_A",
    "Ne",
    "NeC",
    "Nm",
    "Np",
    "Oe",
    "P",
    "PPCM",
    "PPI",
    "PSH",
    "Pa",
    "Phi_0",
    "Quantity",
    "R",
    "RKM",
    "R_K",
    "R_K90",
    "R_inf",
    "R_∞",
    "Rd",
    "Ry",
    "S",
    "SPL",
    "St",
    "Sv",
    "System",
    "T",
    "Ta",
    "Td",
    "Tj",
    "Tt",
    "U",
    "UK_bbl",
    "UK_bushel",
    "UK_cup",
    "UK_cwt",
    "UK_fluid_ounce",
    "UK_force_ton",
    "UK_gallon",
    "UK_gill",
    "UK_horsepower",
    "UK_hundredweight",
    "UK_pint",
    "UK_pk",
    "UK_quart",
    "UK_ton",
    "UK_ton_force",
    "US_cwt",
    "US_dry_barrel",
    "US_dry_gallon",
    "US_dry_pint",
    "US_dry_quart",
    "US_fluid_dram",
    "US_fluid_ounce",
    "US_force_ton",
    "US_hundredweight",
    "US_international_ampere",
    "US_international_ohm",
    "US_international_volt",
    "US_liquid_cup",
    "US_liquid_dram",
    "US_liquid_fifth",
    "US_liquid_gallon",
    "US_liquid_gill",
    "US_liquid_ounce",
    "US_liquid_quart",
    "US_pint",
    "US_shot",
    "US_therm",
    "US_ton",
    "US_ton_force",
    "Unit",
    "UnitsContainer",
    "V",
    "VA",
    "V_90",
    "V_US",
    "V_it",
    "W",
    "W_90",
    "Wb",
    "Wh",
    "Xu_Cu",
    "Xu_Mo",
    "Z_0",
    "a",
    "a0",
    "a_0",
    "a_u_action",
    "a_u_current",
    "a_u_electric_field",
    "a_u_energy",
    "a_u_force",
    "a_u_intensity",
    "a_u_length",
    "a_u_mass",
    "a_u_temp",
    "a_u_time",
    "abA",
    "abC",
    "abF",
    "abH",
    "abS",
    "abV",
    "abampere",
    "abcoulomb",
    "aberdeen",
    "abfarad",
    "abhenry",
    "abmho",
    "abohm",
    "absiemens",
    "abvolt",
    "abΩ",
    "acre",
    "acre_feet",
    "acre_foot",
    "add_context",
    "alpha",
    "amp",
    "ampere",
    "ampere_hour",
    "ampere_turn",
    "amu",
    "angstrom",
    "angstrom_star",
    "angular_degree",
    "angular_minute",
    "angular_second",
    "ap_dr",
    "ap_lb",
    "ap_oz",
    "apothecary_dram",
    "apothecary_ounce",
    "apothecary_pound",
    "arc_minute",
    "arc_second",
    "arcdeg",
    "arcdegree",
    "arcmin",
    "arcminute",
    "arcsec",
    "arcsecond",
    "are",
    "astronomical_unit",
    "at",
    "atm",
    "atm_l",
    "atmosphere",
    "atmosphere_liter",
    "atomic_mass_constant",
    "atomic_unit_of_action",
    "atomic_unit_of_current",
    "atomic_unit_of_electric_field",
    "atomic_unit_of_energy",
    "atomic_unit_of_force",
    "atomic_unit_of_intensity",
    "atomic_unit_of_length",
    "atomic_unit_of_mass",
    "atomic_unit_of_temperature",
    "atomic_unit_of_time",
    "au",
    "auto_reduce_dimensions",
    "autoconvert_offset_to_baseunit",
    "autoconvert_to_preferred",
    "avdp_dram",
    "avdp_ounce",
    "avdp_pound",
    "avogadro_constant",
    "avogadro_number",
    "avoirdupois_dram",
    "avoirdupois_ounce",
    "avoirdupois_pound",
    "b",
    "bag",
    "bar",
    "barad",
    "barie",
    "barn",
    "barrel",
    "barrie",
    "baryd",
    "barye",
    "baud",
    "bbl",
    "becquerel",
    "beer_barrel",
    "beer_bbl",
    "big_point",
    "biot",
    "biot_turn",
    "bit",
    "bits_per_pixel",
    "blob",
    "board_feet",
    "board_foot",
    "bohr",
    "bohr_magneton",
    "bohr_radius",
    "boiler_horsepower",
    "boltzmann_constant",
    "bp",
    "bpp",
    "bps",
    "british_thermal_unit",
    "bu",
    "buckingham",
    "bushel",
    "byte",
    "c",
    "c_0",
    "c_1",
    "c_2",
    "cables_length",
    "cache_folder",
    "cal",
    "cal_15",
    "cal_it",
    "cal_th",
    "calorie",
    "candela",
    "candle",
    "carat",
    "case_sensitive",
    "cc",
    "cd",
    "celsius",
    "centimeter",
    "centimeter_H2O",
    "centimeter_Hg",
    "centimeter_Hg_0C",
    "centipoise",
    "centuries",
    "century",
    "chain",
    "characteristic_impedance_of_vacuum",
    "check",
    "cicero",
    "circle",
    "circular_mil",
    "classical_electron_radius",
    "clausius",
    "cmH2O",
    "cmHg",
    "cm_1",
    "cm_H2O",
    "cm_Hg",
    "cmil",
    "common_year",
    "conductance_quantum",
    "context",
    "conventional_ampere_90",
    "conventional_coulomb_90",
    "conventional_farad_90",
    "conventional_henry_90",
    "conventional_josephson_constant",
    "conventional_mercury",
    "conventional_ohm_90",
    "conventional_volt_90",
    "conventional_von_klitzing_constant",
    "conventional_water",
    "conventional_watt_90",
    "convert",
    "cooling_tower_ton",
    "coulomb",
    "coulomb_constant",
    "count",
    "counts_per_second",
    "cp",
    "cps",
    "css_pixel",
    "ct",
    "cu_ft",
    "cu_in",
    "cu_yd",
    "cubic_centimeter",
    "cubic_feet",
    "cubic_foot",
    "cubic_inch",
    "cubic_yard",
    "cup",
    "curie",
    "cwt",
    "cycle",
    "d",
    "dB",
    "dBm",
    "dBu",
    "d_220",
    "dalton",
    "darcy",
    "day",
    "debye",
    "decade",
    "decibel",
    "decibelmicrowatt",
    "decibelmilliwatt",
    "decimeter",
    "decitex",
    "default_as_delta",
    "default_format",
    "default_system",
    "define",
    "deg",
    "degC",
    "degF",
    "degK",
    "degR",
    "degRe",
    "degree",
    "degreeC",
    "degreeE",
    "degreeF",
    "degreeK",
    "degreeN",
    "degreeR",
    "degreeRe",
    "degree_Celsius",
    "degree_E",
    "degree_Fahrenheit",
    "degree_Kelvin",
    "degree_N",
    "degree_Rankine",
    "degree_Reaumur",
    "degree_Réaumur",
    "degree_east",
    "degree_north",
    "degreesE",
    "degreesN",
    "degrees_E",
    "degrees_N",
    "degrees_east",
    "degrees_north",
    "delta_celsius",
    "delta_degC",
    "delta_degF",
    "delta_degRe",
    "delta_degreeC",
    "delta_degreeF",
    "delta_degreeRe",
    "delta_degree_Celsius",
    "delta_degree_Fahrenheit",
    "delta_degree_Reaumur",
    "delta_degree_Réaumur",
    "delta_fahrenheit",
    "delta_reaumur",
    "delta_réaumur",
    "den",
    "denier",
    "dgal",
    "didot",
    "dirac_constant",
    "disable_contexts",
    "dot",
    "dots_per_inch",
    "dpi",
    "dqt",
    "dr",
    "drachm",
    "dram",
    "dry_barrel",
    "dry_gallon",
    "dry_pint",
    "dry_quart",
    "dtex",
    "dwt",
    "dyn",
    "dyne",
    "e",
    "eV",
    "electric_constant",
    "electrical_horsepower",
    "electron_g_factor",
    "electron_mass",
    "electron_volt",
    "elementary_charge",
    "enable_contexts",
    "entropy_unit",
    "enzyme_unit",
    "enzymeunit",
    "eon",
    "eps0",
    "eps_0",
    "epsilon_0",
    "erg",
    "esu",
    "eu",
    "eulers_number",
    "fahrenheit",
    "farad",
    "faraday",
    "faraday_constant",
    "fathom",
    "feet",
    "feet_H2O",
    "femtometer",
    "fermi",
    "fifteen_degree_calorie",
    "fifth",
    "fine_structure_constant",
    "first_radiation_constant",
    "fldr",
    "floz",
    "fluid_dram",
    "fluid_ounce",
    "fluidram",
    "fm",
    "fmt_locale",
    "foot",
    "foot_H2O",
    "foot_per_second",
    "foot_pound",
    "footpound",
    "force_gram",
    "force_kilogram",
    "force_long_ton",
    "force_metric_ton",
    "force_ndarray",
    "force_ndarray_like",
    "force_ounce",
    "force_pound",
    "force_short_ton",
    "force_t",
    "force_ton",
    "fortnight",
    "fps",
    "franklin",
    "ft",
    "ftH2O",
    "ft_lb",
    "fur",
    "furlong",
    "g",
    "g0",
    "g_0",
    "g_e",
    "g_n",
    "gal",
    "galileo",
    "gallon",
    "gamma",
    "gamma_mass",
    "gauss",
    "get_base_units",
    "get_compatible_units",
    "get_dimensionality",
    "get_group",
    "get_name",
    "get_root_units",
    "get_symbol",
    "get_system",
    "gf",
    "gi",
    "gilbert",
    "gill",
    "gon",
    "gpm",
    "gr",
    "grad",
    "grade",
    "grain",
    "gram",
    "gram_force",
    "gravitational_constant",
    "gravity",
    "gray",
    "gregorian_year",
    "h",
    "ha",
    "hand",
    "hartree",
    "hartree_energy",
    "hbar",
    "hectare",
    "hectopascal",
    "henry",
    "hertz",
    "hogshead",
    "horsepower",
    "hour",
    "hp",
    "hr",
    "hundredweight",
    "hydraulic_horsepower",
    "impedance_of_free_space",
    "imperial_barrel",
    "imperial_bbl",
    "imperial_bu",
    "imperial_bushel",
    "imperial_cp",
    "imperial_cup",
    "imperial_fldr",
    "imperial_floz",
    "imperial_fluid_drachm",
    "imperial_fluid_dram",
    "imperial_fluid_ounce",
    "imperial_fluid_scruple",
    "imperial_gal",
    "imperial_gallon",
    "imperial_gi",
    "imperial_gill",
    "imperial_minim",
    "imperial_peck",
    "imperial_pint",
    "imperial_pk",
    "imperial_pt",
    "imperial_qt",
    "imperial_quart",
    "in",
    "inHg",
    "in_Hg",
    "inch",
    "inch_H2O_39F",
    "inch_H2O_60F",
    "inch_Hg",
    "inch_Hg_32F",
    "inch_Hg_60F",
    "inches",
    "international_british_thermal_unit",
    "international_calorie",
    "international_feet",
    "international_foot",
    "international_inch",
    "international_inches",
    "international_knot",
    "international_mile",
    "international_steam_table_calorie",
    "international_yard",
    "is_compatible_with",
    "jig",
    "josephson_constant",
    "joule",
    "julian_year",
    "jute",
    "k",
    "k_B",
    "k_C",
    "karat",
    "kat",
    "katal",
    "kayser",
    "kelvin",
    "kgf",
    "kilogram",
    "kilogram_force",
    "kilojoule",
    "kilometer",
    "kilometer_per_hour",
    "kilometer_per_second",
    "kip",
    "kip_per_square_inch",
    "knot",
    "knot_international",
    "kph",
    "kps",
    "ksi",
    "kt",
    "l",
    "lambda",
    "lambert",
    "langley",
    "lattice_spacing_of_Si",
    "lb",
    "lbf",
    "lbt",
    "league",
    "leap_year",
    "li",
    "light_year",
    "lightyear",
    "link",
    "liquid_cup",
    "liquid_gallon",
    "liquid_gill",
    "liquid_pint",
    "liquid_quart",
    "liter",
    "litre",
    "lm",
    "ln10",
    "load_definitions",
    "long_hundredweight",
    "long_ton",
    "long_ton_force",
    "lumen",
    "lunar_month",
    "lux",
    "lx",
    "ly",
    "m",
    "m_e",
    "m_n",
    "m_p",
    "m_u",
    "magnetic_constant",
    "magnetic_flux_quantum",
    "mas",
    "maxwell",
    "mean_international_ampere",
    "mean_international_ohm",
    "mean_international_volt",
    "mercury",
    "mercury_60F",
    "meter",
    "meter_per_second",
    "metre",
    "metric_horsepower",
    "metric_ton",
    "metric_ton_force",
    "mho",
    "mi",
    "microgram",
    "microliter",
    "micrometer",
    "micromole",
    "micron",
    "mil",
    "mil_length",
    "mile",
    "mile_per_hour",
    "millennia",
    "millennium",
    "milliarcsecond",
    "millibar",
    "milligram",
    "millimeter",
    "millimeter_Hg",
    "millimeter_Hg_0C",
    "min",
    "minim",
    "minute",
    "mmHg",
    "mm_Hg",
    "mol",
    "molar",
    "molar_gas_constant",
    "mole",
    "molec",
    "molecule",
    "month",
    "mph",
    "mpl_formatter",
    "mps",
    "mu0",
    "mu_0",
    "mu_B",
    "mu_N",
    "nautical_mile",
    "neper",
    "neutron_mass",
    "newton",
    "newtonian_constant_of_gravitation",
    "nit",
    "nmi",
    "non_int_type",
    "nuclear_magneton",
    "number_english",
    "number_meter",
    "oct",
    "octave",
    "octet",
    "oersted",
    "ohm",
    "ohm_90",
    "ohm_US",
    "ohm_it",
    "oil_barrel",
    "oil_bbl",
    "ounce",
    "ounce_force",
    "oz",
    "ozf",
    "ozt",
    "params",
    "parse_expression",
    "parse_pattern",
    "parse_unit_name",
    "parse_units",
    "parse_units_as_container",
    "parsec",
    "particle",
    "pascal",
    "pc",
    "pdl",
    "peak_sun_hour",
    "peck",
    "pel",
    "pennyweight",
    "percent",
    "perch",
    "pi",
    "pi_theorem",
    "pica",
    "picture_element",
    "pint",
    "pixel",
    "pixels_per_centimeter",
    "pixels_per_inch",
    "pk",
    "planck_constant",
    "planck_current",
    "planck_length",
    "planck_mass",
    "planck_temperature",
    "planck_time",
    "point",
    "poise",
    "pole",
    "pond",
    "pound",
    "pound_force",
    "pound_force_per_square_inch",
    "poundal",
    "pp",
    "ppi",
    "ppm",
    "preprocessors",
    "printers_dpi",
    "printers_pica",
    "printers_point",
    "proton_mass",
    "psi",
    "pt",
    "px",
    "qt",
    "quad",
    "quadrillion_Btu",
    "quart",
    "quarter",
    "r_e",
    "rad",
    "radian",
    "rads",
    "rankine",
    "rd",
    "reaumur",
    "reciprocal_centimeter",
    "refrigeration_ton",
    "rem",
    "remove_context",
    "revolution",
    "revolutions_per_minute",
    "revolutions_per_second",
    "reyn",
    "rhe",
    "rod",
    "roentgen",
    "rpm",
    "rps",
    "rutherford",
    "rydberg",
    "rydberg_constant",
    "réaumur",
    "röntgen",
    "s",
    "scaled_point",
    "scruple",
    "sec",
    "second",
    "second_radiation_constant",
    "section",
    "separate_format_defaults",
    "set_fmt_locale",
    "setup_matplotlib",
    "sft",
    "shake",
    "short_hundredweight",
    "short_ton",
    "short_ton_force",
    "shot",
    "sidereal_day",
    "sidereal_month",
    "sidereal_year",
    "siemens",
    "sievert",
    "sigma",
    "sigma_e",
    "slinch",
    "slm",
    "slpm",
    "slug",
    "slugette",
    "smi",
    "sound_pressure_level",
    "speed_of_light",
    "sq_deg",
    "sq_ft",
    "sq_in",
    "sq_mi",
    "sq_perch",
    "sq_pole",
    "sq_rod",
    "sq_yd",
    "sqdeg",
    "square_degree",
    "square_feet",
    "square_foot",
    "square_inch",
    "square_inches",
    "square_league",
    "square_mile",
    "square_rod",
    "square_survey_mile",
    "square_yard",
    "sr",
    "standard_atmosphere",
    "standard_gravity",
    "standard_liter_per_minute",
    "statA",
    "statC",
    "statF",
    "statH",
    "statT",
    "statV",
    "statWb",
    "statampere",
    "statcoulomb",
    "statfarad",
    "stathenry",
    "statmho",
    "statohm",
    "stattesla",
    "statvolt",
    "statweber",
    "statΩ",
    "stefan_boltzmann_constant",
    "steradian",
    "stere",
    "stilb",
    "stokes",
    "stone",
    "super_feet",
    "super_foot",
    "superficial_feet",
    "superficial_foot",
    "survey_foot",
    "survey_link",
    "survey_mile",
    "sv",
    "svedberg",
    "sverdrup",
    "synodic_month",
    "sys",
    "t",
    "tTNT",
    "t_force",
    "tablespoon",
    "tansec",
    "tbsp",
    "teaspoon",
    "technical_atmosphere",
    "tesla",
    "tex",
    "tex_cicero",
    "tex_didot",
    "tex_pica",
    "tex_point",
    "tf",
    "th",
    "therm",
    "thermochemical_british_thermal_unit",
    "thermochemical_calorie",
    "thm",
    "thomson_cross_section",
    "thou",
    "tlb",
    "toe",
    "ton",
    "ton_TNT",
    "ton_force",
    "ton_of_refrigeration",
    "tonne",
    "tonne_of_oil_equivalent",
    "torr",
    "townsend",
    "toz",
    "tropical_month",
    "tropical_year",
    "troy_ounce",
    "troy_pound",
    "tsp",
    "turn",
    "u",
    "unified_atomic_mass_unit",
    "unit_pole",
    "us_statute_mile",
    "vacuum_permeability",
    "vacuum_permittivity",
    "volt",
    "volt_ampere",
    "von_klitzing_constant",
    "water",
    "water_39F",
    "water_4C",
    "water_60F",
    "watt",
    "watt_hour",
    "watthour",
    "weber",
    "week",
    "wien_frequency_displacement_law_constant",
    "wien_u",
    "wien_wavelength_displacement_law_constant",
    "wien_x",
    "with_context",
    "wraps",
    "x_unit_Cu",
    "x_unit_Mo",
    "yard",
    "yd",
    "year",
    "yr",
    "zeta",
    "°C",
    "°F",
    "°K",
    "°R",
    "°Re",
    "µ",
    "µ_0",
    "µ_B",
    "µ_N",
    "Å",
    "Å_star",
    "ångström",
    "ørsted",
    "ħ",
    "Δcelsius",
    "ΔdegC",
    "ΔdegF",
    "ΔdegRe",
    "ΔdegreeC",
    "ΔdegreeF",
    "ΔdegreeRe",
    "Δdegree_Réaumur",
    "Δfahrenheit",
    "Δreaumur",
    "Δréaumur",
    "Δ°C",
    "Δ°F",
    "Δ°Re",
    "Φ_0",
    "Ω",
    "Ω_90",
    "Ω_US",
    "Ω_it",
    "α",
    "γ",
    "ε_0",
    "ζ",
    "λ",
    "μ",
    "π",
    "σ",
    "σ_e",
    "ℎ",
    "Å",
]
